# docker-compose.yaml
version: "2"
services:
  WebApp:
    # container_name: Web_admin
    image: candymi/cfweb:latest
    restart: always
    volumes:
      - ../script/:/app/script/
    ports:
      - "80:8080"
    depends_on:
      - WebDB
    links:
      - WebDB
    networks:
      - local

  WebDB:
    # container_name: Web_DB
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=cfadmin
    volumes:
      - ../lualib/admin/db/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

networks:
  local:
    driver: bridge
